### ISSUE TITLE
Support symfony 3.x css-selectors package

### ISSUE THREAD

**Issue by robations** [FluentDOM/Selectors-Symfony#1]
The old problem that it is impossible or impractical to have two versions of the same package installed :(

In Symfony 3 there are some small changes:
- The `CssSelector` class has gone, we must use `CssSelectorConverter`. Compare docs for [2.7](https://symfony.com/doc/2.7/components/css_selector.html) and [3.1](https://symfony.com/doc/3.1/components/css_selector.html).
- `CssSelectorConverter` must be instantiated (`xPath` method is no longer static).

Ideally you could support both 2 and 3 transparently but not sure how this integrates with FluentDOM. So, I'd rather wait for advice before attempting a PR.

**Comment by ThomasWeinert** [comment]
I suggest using two branches (1.x and 2.x) in the integration repository. Updating the 1.0 branch for the CSSSelectors 2.7 and implement the 3.1 in master and a 2.0 release branch.

**Comment by ThomasWeinert** [comment]
Done.
